on:
  push:
    branches:
      - dev
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout de c贸digo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalaci贸n de dependencias para pruebas
        run: pip install --no-cache-dir --upgrade -r requirements.txt -r requirements.test.txt

      - name: Ejecuci贸n de pruebas
        run: pytest -q --tb=short --disable-warnings --maxfail=1

      - name: Definici贸n de variables adicionales de ambiente
        id: vars
        run: |
          echo "CURRENT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Configurar acceso a GitHub Container Registry 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir imagen de contenedor
        env:
          GITHUB_REPO: ${{ github.repository }}
        run: |
          docker build \
            -t ghcr.io/${GITHUB_REPO,,}:${{ github.sha }} \
            -t ghcr.io/${GITHUB_REPO,,}:${{ env.CURRENT_BRANCH }} \
            .

      - name: Subir imagen de contenedor
        env:
          GITHUB_REPO: ${{ github.repository }}
        run: |
          docker push ghcr.io/${GITHUB_REPO,,}:${{ github.sha }} \
          && docker push ghcr.io/${GITHUB_REPO,,}:${{ env.CURRENT_BRANCH }}
